### ISSUE TITLE
Daily Client Request exceeded

### ISSUE THREAD

**Issue by Daniel131313** [mileswd/mac2imgur#104] opened 2016-09-20 21:48 UTC
Hey all, 

I'm in med school and have come to depend on the imgur screenshots heavily for my studies. For the life of me I cannot get the imgur2mac uploader to work anymore. Whenever I take a screen shot it says "daily client request exceeded". I know others have had similar issues and resolved them. I attempted to follow their trouble shooting steps but I still get the same error upon reopening imgur. I would be sincerely grateful for a very detailed step by step process in how to fix it. Sorry I'm very naive when it comes to computers/computer programming. Thanks any advance!

**Comment by mileswd** [comment] 2016-09-20 22:03
Duplicate of #100

(Take a look at #100 for a solution!)

**Closed by mileswd** 2016-09-20 22:03 UTC

**Comment by Daniel131313** [comment] 2016-09-21 21:50
Do you have a link to accept donations? Thanks for the app


________________________________

**Comment by ahmadawais** [comment] 2016-09-21 23:53
@Daniel131313 No need to be sorry about anything. Just take a look at the solutions offered. [This](https://github.com/mileswd/mac2imgur/issues/100#issuecomment-246596977) one helped me. Before you follow it, just remove your app delete it from the Applications folder. Download a new version from [here](https://github.com/mileswd/mac2imgur/releases/tag/b219).
