### ISSUE TITLE
Daily client requests exceeded

### ISSUE THREAD

**Issue by Jofkos** [mileswd/mac2imgur#100] opened 2016-09-04 17:40 UTC
![The notification](http://i.imgur.com/GS39rEZ.png)

since today I get a "daily client requests exceeded" notification.
But, as far as documented [here](https://api.imgur.com/#limits), the limit is at 
>  approximately 1,250 uploads per day or approximately 12,500 requests per day.  

I don't think i uploaded 1'250 screenshots today 😮

Is there something I'm doing wrong or is mac2imgur sending too much requests?

**Comment by RedPlanetofMars** [comment] 2016-09-04 18:10
I am having the same problem... Joined github to address this issue, glad to know that it's not my end.

**Comment by iCHAIT** [comment] 2016-09-04 18:19
Facing the same issue :(

**Comment by mileswd** [comment] 2016-09-04 19:06
My apologies about this issue - we've hit the Imgur API rate limit, which prevents the combined usage of all users from exceeding 12,500 requests (or 1,250 uploads) per day.

This limit resets every day and until it resets, there's little we can do.

I sent Imgur an email about this issue on August 14th (in relation to #86) but unfortunately they haven't replied yet.

**Comment by EduardoRT** [comment] 2016-09-04 21:17
What about adding an easy way to modify the API key so we could use our own?

**Comment by tommiv** [comment] 2016-09-05 08:37
I always thought that api limit is depending on user api token, not an application token. Since I'm obviously wrong, it would be great to get an ability to change the app token manually.

**Comment by s1lviu** [comment] 2016-09-05 10:00
Same issue here. 
I tought like @tommiv and I agree with that.

**Comment by mated77** [comment] 2016-09-05 10:44
Same Problem here. @mileswd Write them another Mail. I think many people are happy like me with the awesome tool you create. But if i can´t upload now quickly my Screens i have to go away. Sadly away from this tool but in first line away from Imgur. Hope they fix it soon. I only read that the commercial API isn´t limited. And as i read it is not possible to get a free Api for every User cause you have to registrar your Application (

**Comment by s1lviu** [comment] 2016-09-05 10:57
The qick hackish solution is to hex-edit the app, find the clientID and clientSecret and replace with yours.
Thanks goes to @g3x0 for the idea.

**Comment by g3x0** [comment] 2016-09-05 11:03
Thanks @s1lviu 

Followup instructions:

0. Create your own imgur app, use mac2imgur:// as callback URL. Save client ID and client secret.
1. Use something like Hex Fiend to edit /Applications/mac2imgur.app/Contents/MacOS/mac2imgur
2. Search for text: "5867856c9027819" and replace with your client id.
3. Search for text: "7c2a63097cbb0f10f260291aab497be458388a64" and replace with your client secret.
4. Restart the app and authenticate again via mac2imgur.

Everything should work now.

**Comment by tommiv** [comment] 2016-09-05 11:05
Will this work? AFAIK mac os uses some kind of package signature and app will fail to start if it has checksum error. I must to admit I don't know if this feature optional, but when I tried to modify some files in i-dont-remember-which app it broke.

**Comment by g3x0** [comment] 2016-09-05 11:07
@tommiv https://i.imgur.com/EjiHM8X.png

It works.

**Comment by mated77** [comment] 2016-09-05 12:05
Works like a charm ;-) Thank you...

**Comment by vaidab** [comment] 2016-09-05 12:57
I have the same issue.

**Comment by cwhite92** [comment] 2016-09-05 14:50
@g3x0's instructions work a charm. The best solution to this is to allow us to set our own client ID and secret in the app I think.

**Comment by vaidab** [comment] 2016-09-05 15:10
Any way to make it work for the non coders out here?

**Comment by tommiv** [comment] 2016-09-05 15:16
It's not that hard, instructions from @g3x0 works great. HexFiend allows you to replace strings in binary as if it was txt document. I believe the only option to resolve this without effort is to wait for ban to expire or to wait for app devs to introduce api key option.

**Comment by Jofkos** [comment] 2016-09-05 15:37
That you @g3x0, nice idea 😄

**Comment by mlebkowski** [comment] 2016-09-05 16:50
This is a simple Terminal command to replace the values for your own:

```sh
sed -i ".bak" -e s/5867856c9027819/CLIENT_ID/ -e s/7c2a63097cbb0f10f260291aab497be458388a64/CLIENT_SECRET/ /Applications/mac2imgur.app/Contents/MacOS/mac2imgur
```

Just replace the `CLIENT_ID` and `CLIENET_SECRET` with your values. Anyone can confirm?

**Comment by mileswd** [comment] 2016-09-05 21:51
@mated77 Thanks for the suggestion -- I've sent Imgur another email, this time I got an automated reply saying that an issue ticket has been created, so hopefully I'll get a response this time!

I'm hoping that since mac2imgur is a free/non-profit open source application, they will allow us something similar to an option they used to offer, called "Heavy Free Usage" - http://web.archive.org/web/20151014051251/http://api.imgur.com/#heavyusage.

--

In regards to modifying the client keys of the executable:

Since I codesign each release, modifying the executable itself will probably invalidate the code signature, likely causing macOS to detect the application as "corrupted".

I'm also not sure if changing the client keys for the same application is against any Imgur API terms of service / acceptable usage policy - so this is probably more of a "last resort" solution.

**Comment by vaidab** [comment] 2016-09-06 06:15
@mlebkowski  I get sed: RE error: illegal byte sequence
sed -i ".bak" -e s/5867856c9027819/fd25.../ -e s/7c2a63097cbb0f10f260291aab497be458388a64/bb71a8ffbfb1c20c09e54ab5642b.../ /Applications/mac2imgur.app/Contents/MacOS/mac2imgur

**Comment by jlsjonas** [comment] 2016-09-12 06:51
@mileswd I guess that an alternative (in case no timely reply comes, since I'm also struck by the "banhammer" now) would be to fork out, having "multiple apps", potentially (hopefully) being allowed to somehow embed them as an option. Although imgur should face it that it'll only cost them more resources in the long run by not handing a "heavy free use" key for mac2imgur

**Comment by mileswd** [comment] 2016-09-12 11:04
For transparency, here is the email exchanges between myself and Imgur API support:

Initial email:

> Hey,

> I maintain an open source, free/non-profit image uploading application (https://github.com/mileswd/mac2imgur).

> Recently we've been running into rate limiting issues ("daily client requests exceeded"), causing the application to become unusable for all users. (We're tracking this issue here: https://github.com/mileswd/mac2imgur/issues/100)

> I recall that Imgur used to offer a "Heavy Free Usage" option (http://web.archive.org/web/20151014051251/http://api.imgur.com/#heavyusage), where non commercial applications could be registered on a whitelist.

> Would it be possible to become whitelisted, or could you provide an alternative solution?

> Thanks in advance - any assistance here would be greatly appreciated.

> Kind regards,
> Miles

Their response:

> Hi Miles,

> Thanks for reaching out about the Imgur API! I'd be happy to help.

> We no longer offer the option of whitelisting clients. As mentioned, in the thread you pointed out, allowing users the option to use their own client IDs would work. Another option would be to cache any GET requests you send on your end. However, if your use case is to upload images, I'm afraid I don't have a work around at the moment.

> Let me know if you have any other questions that I can help to answer.

> Best,

It's a shame that they don't offer whitelisting anymore, because using alternative client IDs would still mean the application has the same amount of API usage / uploads.

We can't really complain however, because this is a free service which Imgur aren't obligated to provide, so the fact they even offer this service is greatly appreciated. :+1:

Here's my current plan so far:

- [ ] Implement a feature which allows changing of the client ID and client secret
- [ ] Re-evaluate our Imgur API Library: We currently use [`ImgurSession`](https://github.com/geoffmacd/ImgurSession) which is maintained by an Imgur API engineer, but I believe it would be possible to reduce unnecessary API requests with a more efficient custom library.

**Comment by jlsjonas** [comment] 2016-09-12 11:14
What I would suggest to avoid each making an app is maybe using a microservice to "hand out" said id's & secrets; having a couple contributors create a set.
this would also prevent issues with non-tech users (a new -preferably unexposed- pair should obviously be hardcoded in case the microservice is down)

the microservice should simply track how many installations got the key, and disable further deployment at a certain limit.

I'd say check in with their support asking if that would be acceptable, though I'm pretty sure that would be the solution with least impact on them (since email confirmed my suspicions that they just use mashable to limit internal api calls & management thereof)

**Comment by tommiv** [comment] 2016-09-12 11:16
I would prefer to just set up my own app id. But your idea is cool indeed, especially for the "non-tech" users.

**Comment by cwhite92** [comment] 2016-09-12 11:16
> because using alternative client IDs would still mean the application has the same amount of API usage / uploads.

I think the upload limit for an application is more than enough for an individual user. If an individual user hits the upload limit on their own application, they're definitely doing something out of the ordinary.

**Comment by jlsjonas** [comment] 2016-09-12 11:19
@cwhite92 an individual user can't possibly use up one app's limits, since their personal limits are 1/25th of the app's limit, which is also why I suggested the microservice to manage those keys (again, mainly thinking about non-tech users)

**Comment by barrierfreeman** [comment] 2016-09-12 11:20
> But your idea is cool indeed, especially for the "non-tech" users.

Non-tech user checking in. 

Would just like to say thanks to Miles for looking at a solution so us luddites can continue to use the app.

**Comment by jlsjonas** [comment] 2016-09-12 11:25
As to this issue specifically, the app should prevent further attempts once this message came in, although from what I've read it wouldn't really matter: hitting the limit 5 times in a month would prevent further access.
maybe check for limits often enough? (since limit checks don't count towards the limit)
talking of which... these could be used as an indication regarding "popularity" of each key pair: cron checking the limits daily, a few minutes before the reset ?)

**Comment by g3x0** [comment] 2016-09-12 11:27
You can combine all the suggestions and provide a complete solution in the following form:

1. Keep using the main API keys as default.
2. Allow for using own API keys per client and suggest this in the following updates so you can encourage users to actually do it before you hit the API limit again.
3. Add a checkbox below the own API keys feature which states that they're enabling you to use their API keys when your default ones hit the limit.
4. Make the microservice rotate the keys when it hits the limit.

**Comment by tommiv** [comment] 2016-09-12 11:29
4. Wouldn't it be easier to "load balance" the keys in a way http-servers does it (round-robin or something more sophisticated)?

**Comment by g3x0** [comment] 2016-09-12 11:37
Yeah, but you need a few API keys for that, not just say 3, because the reason some users will actually set their own API keys is to never hit that limit anymore in their personal use of the app. So if you load balance and hit the limit on some of the users' API keys, you'll have some unsatisfied users. 

That's why I think you should use the microservice only when the main API fails. But, again, you can combine the suggestions; use the main API to the limit, then load balance the keys in the microservice.

Although, I realise it's getting pretty complex for a simple image uploading tool. So, even if you just add the fields for own API keys, that'd be good enough.

**Comment by barrierfreeman** [comment] 2016-09-12 11:49
As an aside, I followed @g3x0 steps for a temporary fix. All went fine until after I saved the binary in Hex Fiend, but now mac2imgur won't run. 

Guess I'll just wait till the professionals get it sorted.

**Comment by jlsjonas** [comment] 2016-09-12 12:28
@g3x0 great idea regarding "share with community", 
though (also @tommiv ) the reason I didn't suggest "keep using the main" is because users are required to authenticate TO an app... thus using round robin or main-by-default would require users to re-authenticate as limits are reached, which would also cause a lot of unnecessary extra calls (though should not affect the limits, in theory)

**Comment by g3x0** [comment] 2016-09-12 12:32
@jlsjonas You're right, I forgot about the authentication process. Although, the limits aren't reached that often. I've been using this app since January and this is the first time it happened, so we might be cool simply ignoring it this time. Also, I guess asking to re-authenticate is way better than just having to sit out for a day until the limit gets reset.

**Comment by jlsjonas** [comment] 2016-09-12 12:33
@g3x0 yes, but the core issue is just that the app is becoming more popular, thus we can't expect this to be a temporary thing.

**Comment by sn0w** [comment] 2016-09-12 12:36
Maybe we could look into the code of Sharex ([getsharex.com]()).
I -never- had an issue like this with their app so maybe they are using the API differently / more efficient.

**Comment by barrierfreeman** [comment] 2016-09-12 12:40
> @g3x0 yes, but the core "issue" is just that the app is becoming more popular, thus we can't expect this to be a temporary thing.

Sierra has broken a few of the other apps, like img.urls, so I guess there is going to be an influx of new users coming up.

**Comment by ahmadawais** [comment] 2016-09-12 14:02
@g3x0 I followed all the steps but it says authentication required. I have authenticated the app several times. What's with that 🔢 
<img width="335" alt="screen shot 2016-09-12 at 7 01 26 pm" src="https://cloud.githubusercontent.com/assets/960133/18438551/58d74770-791b-11e6-829b-1b439f56f5c2.png">

**Comment by jlsjonas** [comment] 2016-09-12 14:25
@mileswd do we wait for an official reply to start preparations?
given what @barrier mentioned it could seem as if mac2imgur stopped working too, while it's only a rate limit issue

**Comment by jaredmfier** [comment] 2016-09-12 17:26
Hm, for some reason after using hex fiend to edit in my own api info, the app refuses to open. Only seems to open when I replace the application with a fresh one.

**Comment by joshfriend** [comment] 2016-09-12 18:20
@vaidab I had to set a few environment variables to get the "illegal byte sequence" error to go away:

```
$ LC_ALL=C LC_TYPE=C LANG=C sed -i ".bak" # etc...
```

**Comment by coryshaw1** [comment] 2016-09-12 20:06
I had to `unset LANG` to get @mlebkowski's method to work. But everything works great now!

Here's my process:

 1) Get the rate limit error
 2) Quit Mac2Imgur
 3) Create new Imgur API credentials here: https://api.imgur.com/oauth2/addclient
   - **Application Name**: Anything
   - **Check**: OAuth 2 authorization with a callback URL
   - **Callback URL**: mac2imgur://
   - **Email**: YourEmail
   - **Description**: Creating to use with Mac2Imgur local application

4) In terminal (replace CLIENT_ID and CLIENT_SECRET with what you receive in Step 3):
```
unset LANG
```
```
sed -i ".bak" -e s/5867856c9027819/CLIENT_ID/ -e s/7c2a63097cbb0f10f260291aab497be458388a64/CLIENT_SECRET/ /Applications/mac2imgur.app/Contents/MacOS/mac2imgur
```
 5) Restart Mac2Imgur and reauthenticate
 6) Welcome back!

NOTE: If you want to start from a fresh install, make sure to open the app for the first time before trying Step 4

![https://i.imgur.com/Y3DFT5W.png](https://i.imgur.com/Y3DFT5W.png)

**Comment by siddharthlatest** [comment] 2016-09-12 22:12
@coryshaw1 that worked like a charm.

**Comment by jaredmfier** [comment] 2016-09-13 04:18
@coryshaw1 Not sure if you know the answer to this, but when trying to log in after replacing the cient ID/client secret with the commands you posted, after pressing allow on the imgur api site I get `{"data":{"error":"Unauthorized","request":"\/oauth2\/authorize","method":"POST"},"success":false,"status":403}`

**Comment by ahmadawais** [comment] 2016-09-13 04:51
@coryshaw1 Didn't work. Step 4 gives this error
```bash
sed -i ".bak" -e sh/5867856c9027819/581fca025a36515/ -e sh/7c2a63097cbb0f10f260291aab497be458388a64/61a61fc254ad57990ec475c5ddbfdf45013fda19/ /Applications/mac2imgur.app/Contents/MacOS/mac2imgur
Password:
sed: 1: "sh/5867856c9027819/581f ...": unterminated substitute pattern
```

How does one reauthenticate? I did change the ID with Hex Fiend.

**Comment by sn0w** [comment] 2016-09-13 07:21
I managed to get it to work without changing locals.

```sh
cd /Applications/mac2imgur.app/Contents/MacOS
mv cp mac2imgur mac2imgur.bak
perl -pi -e 's/5867856c9027819/your-id/g' mac2imgur
perl -pi -e 's/7c2a63097cbb0f10f260291aab497be458388a64/your-token/g' mac2imgur
```

After the replacement mac2imgur starts and opens your browser where you have to re-authenticate again.

**Comment by coryshaw1** [comment] 2016-09-13 12:49
@ahmadawais Try changing your sed terminal command to use `s/` instead of `sh/` on your searches:

```
sed -i ".bak" -e s/5867856c9027819/581fca025a36515/ -e s/7c2a63097cbb0f10f260291aab497be458388a64/61a61fc254ad57990ec475c5ddbfdf45013fda19/ /Applications/mac2imgur.app/Contents/MacOS/mac2imgur
```

**Comment by ahmadawais** [comment] 2016-09-17 16:38
Thanks, @sn0w @coryshaw1  I downloaded and installed a new Mac2Imgur and then followed @sn0w 's steps and its still working.

**Comment by AustinPaquette** [comment] 2016-09-20 19:43
@sn0w thank for you for saving me the time to write this out myself. Appreciate it. 😄

**Comment by mileswd** [comment] 2016-09-20 22:02
Hey all,

Still working on a conclusive solution, but in the meantime here's a version of mac2imgur you can use:

[mac2imgur.zip](https://github.com/mileswd/mac2imgur/files/483689/mac2imgur.zip)


(It's no different from the latest version, except with different client ID and client secret keys)

**Comment by Daniel131313** [comment] 2016-09-20 22:51
Steps 1-5 worked for me, pain in the ass but I'm super grateful to all involved here and at imgur. If your having persistent trouble I would read thread 103 as well. Thanks again mileswd and others!

**Comment by mileswd** [comment] 2016-09-21 17:46
Great news - looks like this is an Imgur issue, which is now fixed! 🎉

Received this from Imgur:

>Hi there,

>Since we last reached out, we have identified a bug that was causing excessive rate limiting. As of 11am PST, a fix will be pushed. We expect that you'll see the changes take effect within 24 hours.

>I’m so sorry for the confusion around this issue! We appreciate your patience in dealing with this problem. 

>Please let us know if have any further questions; I'd be happy to help.

>Best,
>Sarah Schaaf
>Director of Community, Imgur

**Closed by mileswd** 2016-09-21 17:46 UTC

**Comment by AustinPaquette** [comment] 2016-09-21 17:51
@mileswd Is there anything problematic about those whom have applied the workarounds?

**Comment by mileswd** [comment] 2016-09-21 17:57
@AustinPaquette There shouldn't be any negative effects caused by the workaround. As it's the application binary that has been modified, the workaround will be reversed whenever the next update for mac2imgur is released anyway.
