### ISSUE TITLE
Drag and Drop does not work

### ISSUE THREAD

**Issue by Aeonofgods** [mileswd/mac2imgur#69] opened 2015-07-24 20:07 UTC
Hey i just downloaded this today! The screenshot upload works fine as does the manual "upload images" button. However dragging a picture to the menu bar icon does not do anything. Suggestions?

I am on a 2013 rMBP 13' on El Capitan public beta 2. Thanks!

**Comment by mileswd** [comment] 2015-07-24 20:16
Duplicate of #64

This issue appears to be fixed in the 4th developer preview `15A226f` but not in the 2nd public beta `15A225f`.

I imagine that this will be fixed in the next public beta (in less than two weeks time).

Unfortunately this is one of the downsides of testing pre-release software! :smile:

**Comment by Aeonofgods** [comment] 2015-07-24 20:17
I totally understand and I can wait. Thanks for the quick response!

**Closed** 2015-07-24 20:23 UTC
