### ISSUE TITLE
Drag/drop images in El Capitan

### ISSUE THREAD

**Issue by sweebee** [mileswd/mac2imgur#64] opened 2015-07-10 16:19 UTC
In Mac Os El Capitan i can't drop images on the icon anymore.

**Comment by mileswd** [comment] 2015-07-10 16:23
It appears that all NSButtons (even those in open/save panels) do not respond to ` registerForDraggedTypes` in El Capitan. I am unsure whether this is a bug, or an intended behaviour change. I shall investigate a workaround if Apple do not fix this in a later developer preview / beta.

Thanks for the report! :+1:

**Comment by mileswd** [comment] 2015-07-21 20:38
This issue appears to be fixed in the latest beta (15A226f) - simply update and this should be fixed! :)

**Closed by mileswd** 2015-07-21 20:38 UTC
